### ISSUE TITLE
TouchEffect seems to be broken in .NET 8

### ISSUE THREAD

**Issue by cytoph** [Axemasta/Maui.TouchEffect#2]
I implemented the touch effect as described in your README in a .NET 8 project (Android only), but it doesn't seem to work. I don't get any building or binding errors and the sound when I tap on an element with the `TouchEffect` attached plays as expected, but the `Command` isn't executed and no ripple animation is shown either (the latter could be related to [this issue](https://github.com/dotnet/maui/issues/17642) and therefore is okay if not currently working). Any idea on what the problem could be, and how to fix it?

**Comment by Axemasta** [comment]
I haven't tested on net8 with any of this so I can't say. Have you tried debugging through and seeing if the [`RaiseCompleted`](https://github.com/Axemasta/Maui.TouchEffect/blob/79baaec67f6a83ecf4c29453050a771b529b31d1/src/Maui.TouchEffect/TouchEffect.cs#L1450) method gets invoked?

**Comment by Axemasta** [comment]
I've updated the library recently to fix an issue with input transparency, it might be worth running the sample and trying to reproduce the issues you are seeing in your app. I have also updated everything to .NET 8 so hopefully building it locally should work.
